services:
  forecast-tool:
    build: .
    image: iacuser/forecast_tool:latest

    ports:
      - "4999:4999"
    volumes:
      # mount local data/output folders into the container so backend scripts can read input files and write results back to the host.
      # left side  = path on YOUR personal machine  (needs updates)
      # right side = path the container sees (filepaths called by Flask routes)
      - ./data:/data
      - ./models:/models
      - ./reports:/reports
    environment:
      - FLASK_ENV=production
      # - SECRET_KEY=   # override with a real secret - irrelevant short term, used if we ever fleshed this out to a multi-user system (used to sign session cookies)
    restart: unless-stopped

    expose:
      - "4999"
  
  # nginx: 
  #   image: nginx:latest
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   depends_on:
  #     - forecast-tool
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro